# Jupiter Notebook y Google colab

### EJERCICIO 1

- ¿Qué es un cuaderno (notebook) Jupyter?

Un cuaderno (notebook) Jupyter es un entorno interactivo de desarrollo que permite combinar código, texto, visualizaciones y otros elementos en un solo documento. Se utiliza ampliamente en ciencia de datos, aprendizaje automático y desarrollo de software por su facilidad para realizar análisis interactivos, pruebas rápidas y documentar el proceso de trabajo.

- ¿Que es una celda? ¿Que tipos de celdas existen?


Una celda es un bloque dentro de un cuaderno Jupyter donde puedes escribir código, texto u otros elementos. Las celdas se pueden ejecutar individualmente, lo que permite realizar pruebas y experimentar sin tener que ejecutar todo el documento.

1. Celda de Código: Es donde escribes y ejecutas código Python (o de otros lenguajes compatibles). Los resultados del código se muestran justo debajo de la celda después de ejecutarla.

2. Celda de Markdown: Se usa para escribir texto en un formato que puede incluir encabezados, listas, enlaces, imágenes y otros elementos de formato. Es ideal para documentar tu trabajo.

3. Celda de Raw: Contiene texto sin procesar que no se ejecuta ni se formatea. Se utiliza para incluir texto que no se desea que se procese en Markdown o código.

● ¿Qué es un entorno de ejecución? ¿Cuánto tiempo dura una sesión de un entorno?

Un entorno de ejecución en Jupyter se refiere al entorno en el cual se ejecuta el código dentro del cuaderno. Esto incluye el intérprete de Python y las bibliotecas instaladas, y se puede personalizar para cumplir con las necesidades específicas del proyecto.

La duración de una sesión de un entorno depende de la configuración del servidor donde esté alojado Jupyter. Si estás usando Jupyter localmente, la sesión dura mientras tengas el cuaderno abierto y el servidor Jupyter corriendo. Si estás usando un servicio en la nube, la sesión puede caducar después de un período de inactividad (que puede variar desde minutos hasta horas), o cuando el servidor se apaga.

### EJERCICIO 2

Las celdas de código de un cuaderno no solo permiten ejecutar instrucciones de Python. Utilizando el símbolo ! (signo de admiración) es posible ejecutar los comandos disponibles desde la línea de comandos de su sistema operativo. De esta manera !ls o !dir (dependiendo el sistema operativo) listan los archivos de la carpeta actual y !pip o !conda permiten administrar los paquetes python.
Experimente la ejecución de varios comandos del sistema operativo a través de celdas de código. Entre las pruebas incluya la invocación de:
- python para determinar la versión instalada.
- pip show nombre (pandas, numpy, tensorflow, etc.) de paquete para saber la versión instalada.
- comandos que permitan crear y eliminar carpetas.


1. Version instalada de python

In [299]:
!python --version

Python 3.11.5


2. Version instalada de paquetes

In [300]:
!pip show pandas
!pip show numpy
!pip show tensorflow


Name: pandas
Version: 1.5.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: C:\Users\VICTUS\anaconda3\Lib\site-packages
Requires: numpy, numpy, python-dateutil, pytz
Required-by: bokeh, bqplot, datasets, datashader, dtreeviz, FuzzyTM, holoviews, hvplot, mlxtend, pandas-flavor, panel, pingouin, pyFUME, seaborn, statsmodels, xarray
Name: numpy
Version: 1.24.4
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: C:\Users\VICTUS\anaconda3\Lib\site-packages
Requires: 
Required-by: astropy, blis, bokeh, Bottleneck, bqplot, contourpy, daal4py, datasets, datashader, datashape, dtreeviz, fst-pso, FuzzyTM, gensim, gym, h5py, holoviews, hvplot, imagecodecs, imageio, imbalanced-learn, keras, matplotlib, minif

3. Creacion y eliminacion de carpetas

In [301]:
!mkdir nueva_carpeta 

In [302]:
!rmdir nueva_carpeta

4. Listar archivos en la carpeta actual

In [303]:
!dir

 El volumen de la unidad C no tiene etiqueta.
 El n�mero de serie del volumen es: CA9D-5C49

 Directorio de c:\Users\VICTUS\Documents\2024\Deep Learning UNLP

17/08/2024  20:56    <DIR>          .
17/08/2024  17:58    <DIR>          ..
17/08/2024  20:55            58.878 practica1.ipynb
               1 archivos         58.878 bytes
               2 dirs  882.179.342.336 bytes libres


### EJERCICIO 3

- Es de google colab, pero yo voy a trabajar local

In [1]:
ruta_arch = './hola.txt' # ruta y nombre a archivo a LEER desde su drive
f = open(ruta_arch, 'r') # abre archivo para leer
print(f.readlines()) # imprime contenido en pantalla
f.close() 

['holaaaa']


In [2]:
ruta_arch = './hola.txt' # ruta y nombre a archivo a ESCRIBIR en su drive
f = open(ruta_arch, 'w') # abre archivo para escribir
texto = 'Esta es una linea de texto\nEsta es otra línea de text'
f.writelines(texto...............................................) # escribe contenido en archivo
f.close() 

# Repaso de Python

En esta sección tiene como objetivo hacer un pequeño repaso y proveer algunos recursos que faciliten el desarrollo
con Python. Para un tutorial desde cero puede consultarse el siguiente video
https://www.youtube.com/watch?v=zAIWnwqHGok. Para repasar estructuras de datos más utilizadas puede
consultarse https://www.youtube.com/watch?v=CCUNuqqn7PQ. Para una referencia rápida, el sitio
https://ipgp.github.io/scientific_python_cheat_sheet/ o https://www.pythoncheatsheet.org/ son buenas
alternativas. Aquí puede repasar temas como operadores, funciones, listas, tuplas, diccionarios, conjuntos, manejo
de strings y lectura/escritura de archivos, entre muchas otras.

### EJERCICIO 1

- Investigue/repase que son las listas, tuplas, conjuntos y diccionarios nativos de Python (puede consultar
https://www.youtube.com/watch?v=CCUNuqqn7PQ) . Utilizando los constructores para cada tipo de dato genere
códigos de ejemplo y recórralos imprimiendo sus valores.


1. LISTAS: colecciones ordenadas y mutables que permiten almacenar elementos de diferentes tipos. Se definen usando corchetes []

In [304]:
lista = [1, 2, 3, 4, 5, 'vale']

for elemento in lista:
    print(elemento)

1
2
3
4
5
vale


2. TUPLAS : Similares a las listas pero inmutables, una vez creadas no se pueden modificar. Se definen utilizando parentesis ()
- Que sea inmutable significa que una vez creada no se pueden cambiar, agregar ni eliminar los elementos que contiene

In [305]:
tupla = (1, 2, 3, 4, 5, 'valeria')

for elemento in tupla:
    print(elemento)

1
2
3
4
5
valeria


3. CONJUNTOS: colecciones desordenadas y sin elementos duplicados. Se definen utilizando llaves {} o la función set().

In [306]:
conjunto = {1, 2, 3, 4, 5, 5}

for elemento in conjunto:
    print(elemento)


1
2
3
4
5


In [307]:
conjunto2 = set([1, 2, 2, 3, 4, 4, 5]) #los elementos duplicados son eliminados

print(conjunto2)

{1, 2, 3, 4, 5}


DICCIONARIOS: colecciones desordenadas de pares clave-valor. Se definen utilizando llaves {}.

In [308]:
diccionario = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

for clave, valor in diccionario.items():
    print(f'Clave: {clave}, Valor: {valor}')


Clave: a, Valor: 10
Clave: b, Valor: 20
Clave: c, Valor: 30
Clave: d, Valor: 40
Clave: e, Valor: 50


### EJERCICIO 2

Genere el código necesario para recorrer simultáneamente 2 listas con la misma cantidad de elementos e imprima los mismos utilizando un único for (tip: función zip).

In [309]:
lista1 = [1, 2, 3, 4, 5]
lista2 = ['a', 'b', 'c', 'd', 'e']

for elem1, elem2 in zip(lista1, lista2):
    print(f'Elemento de lista 1: {elem1}      Elemento de lista 2: {elem2}')


Elemento de lista 1: 1      Elemento de lista 2: a
Elemento de lista 1: 2      Elemento de lista 2: b
Elemento de lista 1: 3      Elemento de lista 2: c
Elemento de lista 1: 4      Elemento de lista 2: d
Elemento de lista 1: 5      Elemento de lista 2: e


### EJERCICIO 3 

Implemente una función que a partir de la lista que recibe cómo parámetro, retorne una nueva lista sin elementos repetidos. Compruebe su correcto funcionamiento.

In [310]:
def funcion (lista):
    conjunto = set(lista)
    lista2 = list(conjunto)
    return lista2


In [311]:
lista1 = [1,2,3,3,3,3,'vale']
funcion (lista1)

[1, 2, 3, 'vale']

### EJERCICIO 4

In [312]:
import math
def funcion2 (x1,y1,x2,y2):
    distancia = math.sqrt((x2 - x1)**2 + (y2-y1)**2)
    return distancia

In [313]:
print('La distancia entre (1,2) y (4,6) es de: ', funcion2 (1,2,4,6))

La distancia entre (1,2) y (4,6) es de:  5.0


### EJERCICIO 5

Investigue y escriba código que demuestre el funcionamiento de los “slices” en listas.

In [314]:
lista = [0,1,2,3,4,5,6,7,8,9,10]

In [315]:
lista[2:5] # recorre desde la posicion hasta la 5 sin incluir

[2, 3, 4]

In [316]:
lista [:4] #recorre hasta la posicion 4 sin incluir

[0, 1, 2, 3]

In [317]:
lista[5:] #recorre desde la posicion 5 incluida

[5, 6, 7, 8, 9, 10]

In [318]:
lista[::2] #recorre toda la lista con un paso de 2

[0, 2, 4, 6, 8, 10]

In [319]:
lista[::-1] #recorre toda la lista de forma invertida

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [320]:
lista[-1] #ultimo elemento de la lista

10

In [321]:
lista [-2] #ante-ultimo elemento de la lista

9

# Numpy

In [322]:
import numpy as np

### EJERCICIO 1

Practique la creación de vectores, matrices y tensores y responda:



1. ¿Qué diferencias hay entre los constructores, array, empty, full, zeros, ones, identity?

- numpy.array() ---> crea un array a partir de un iterable, permitiendo la conversión de listas, tuplas, u otros arrays en un array de NumPy. Puedes especificar el tipo de datos con dtype.

In [323]:
vector = np.array([1, 2, 3, 4])
matriz = np.array([[1, 2], [3, 4]])
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Vector:\n", vector)
print(' ')
print("Matriz:\n", matriz)
print(' ')
print("Tensor:\n", tensor)

Vector:
 [1 2 3 4]
 
Matriz:
 [[1 2]
 [3 4]]
 
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


- numpy.empty()---> Crea un array con una forma y tipo de datos especificados sin inicializar los valores. Los valores son indeterminados (residuos de memoria).

In [324]:
array_vacio = np.empty((2, 3))
print(array_vacio)

[[ 0.50556616  1.10055167 -0.56210989]
 [ 0.39060392 -2.58386111  0.01953343]]


- numpy.full() ---> Crea un array con una forma y tipo de datos especificados, y lo llena con un valor específico.

In [325]:
array_lleno = np.full((2, 3), 7)
print(array_lleno)

[[7 7 7]
 [7 7 7]]


- numpy.zeros() ---> Crea un array con una forma y tipo de datos especificados, y lo llena con ceros.

In [326]:
array_ceros = np.zeros((2, 3))
print(array_ceros)

[[0. 0. 0.]
 [0. 0. 0.]]


- numpy.ones() ---> Crea un array con una forma y tipo de datos especificados, y lo llena con unos.

In [327]:
array_unos = np.ones((2, 3))
print(array_unos)

[[1. 1. 1.]
 [1. 1. 1.]]


- numpy.identity() ---> crea una matriz identidad cuadrada con unos en la diagonal principal y ceros en el resto

In [328]:
matriz_identidad = np.identity(3)
print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. ¿Qué tipos de datos pueden utilizarse? ¿En qué se diferencian? ¿Cuál es el tipo que se toma por
defecto?¿Es siempre el mismo?


NumPy soporta varios tipos de datos (dtype), que permiten almacenar diferentes tipos de información en un array.

- Enteros ('int') --> Existen diferentes tamaños, como int8, int16, int32, y int64.

In [329]:
array_int32 = np.array([1, 2, 3], dtype=np.int32)
print(array_int32)


[1 2 3]


- Punto flotante ('float') --> Los tamaños más comunes son float32 y float64.

In [330]:
array_float64 = np.array([1.1, 2.2, 3.3], dtype=np.float64)
print(array_float64)

[1.1 2.2 3.3]


- Complejos ('complex') --> Representan números complejos con parte real e imaginaria. Los tamaños comunes son complex64 y complex128.

In [331]:
array_complex128 = np.array([1+2j, 3+4j], dtype=np.complex128)
print(array_complex128)

[1.+2.j 3.+4.j]


- Booleanos ('bool') --> True or False

In [332]:
array_bool = np.array([True, False, True], dtype=np.bool_)
print(array_bool)

[ True False  True]


- Cadenas de caracteres ('str') --> Representan secuencias de caracteres. La longitud se puede especificar, como str_ (por defecto no se especifica longitud).

In [333]:
array_str = np.array(["me", "llamo", "valeria"], dtype=np.str_)
print(array_str)

['me' 'llamo' 'valeria']


TIPO DE DATO PREDETERMINADO

Para algunos constructores como zeros() y ones(), el tipo de datos predeterminado es float64. Esto significa que si no especificas un tipo de datos al crear un array, NumPy usará float64 por defecto para estos tipos de arrays.

In [334]:
array_zeros_default = np.zeros((2, 3))
print(array_zeros_default.dtype)

float64


3. ¿Qué funciones se pueden utilizar para generar arreglos con números aleatorios?


numpy.random.rand() --> Genera un arreglo con numeros aleatorios uniformemente distribuidos en el intervalo [0,1)

In [335]:
array_rand = np.random.rand(2, 3)
print(array_rand)

[[0.14972224 0.54780241 0.00056175]
 [0.54399467 0.14333062 0.10819356]]


numpy.random.randn() --> Genera un arreglo con numeros aleatorios de una distribucion normal estandar (media 0 y desviacion estandar 1)

In [336]:
array_randn = np.random.randn(2, 3)
print(array_randn)

[[ 1.21579584  0.24806151 -0.61721753]
 [ 1.05754769 -0.17307939 -0.89722628]]


numpy.random.randint() --> Generaa un arreglo de numeros enteros en un rango especifico

In [337]:
array_randint = np.random.randint(1, 10, (2, 3))
print(array_randint)

[[6 7 7]
 [2 6 9]]


### EJERCICIO 2

Investigue y ejemplifique las funciones relacionadas al tamaño de los arrays de Numpy:

1. ¿Para qué sirven las funciones shape, len, ndim, size?

- shape --> Devuelve una tupla que representa las dimensiones del arreglo. 

In [338]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array.shape

(2, 3)

- len() --> Devuelve el número de elementos en la primera dimensión del array. Es útil para arrays unidimensionales, pero en arrays multidimensionales, solo muestra el tamaño de la primera dimensión.

In [339]:
len(array)

2

- ndim --> Devuelve el número de dimensiones (ejes) del array.

In [340]:
array.ndim

2

- size --> Devuelve el número total de elementos en el array, es decir, el producto de las dimensiones.

In [341]:
array.size


6

### EJERCICIO 3

Practique funciones de agregación (sum, min, max, etc.) sobre vectores, matrices y tensores. Enumere y pruebe
todas las funciones que encuentre y responda:
- ¿Estas funciones se aplican a todos los datos del array o pueden realizarse sobre dimensiones
particulares? Ejemplifique.

In [342]:
vector = np.array([1, 2, 3, 4, 5])

- sum() --> calcula la suma de todos los elementos en el array

In [343]:
np.sum(vector)

15

- min() --> encuentra el valor minimo del array

In [344]:
np.min(vector)

1

- max() --> encuentra el valor maximo del array

In [345]:
np.max(vector)


5

- mean() --> calcula el promedio de todos los elementos del array

In [346]:
np.mean(array)

3.5

Las funciones de agregación pueden aplicarse a todas las dimensiones del array o a dimensiones específicas usando el argumento axis.

- axis=None: Aplica la función a todos los elementos del array (total).
- axis=0: Aplica la función a lo largo del eje 0 (filas en una matriz).
- axis=1: Aplica la función a lo largo del eje 1 (columnas en una matriz).

In [347]:

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Suma total:", np.sum(matriz)) 

print("Suma por columnas:", np.sum(matriz, axis=0)) 

print("Suma por filas:", np.sum(matriz, axis=1))  


Suma total: 45
Suma por columnas: [12 15 18]
Suma por filas: [ 6 15 24]


### EJERCICIO 4 

Investigue y realice ejemplos que utilicen funciones para manipular elementos de arreglos (append, insert, delete,
etc.) y arreglos entre sí (vstack, hstack, contacenate, etc.)


- np.append() --> agrega elementos al final del array

In [348]:
array = np.array([1, 2, 3])
appended_array = np.append(array, [4, 5])
appended_array

array([1, 2, 3, 4, 5])

- np.insert() --> inserta valores en un array en posiciones especificas

In [349]:
array = np.array([1, 2, 3 ,4, 6])

inserted_array = np.insert(array, 4, 5) #inserto el 5 en la posicion 4
inserted_array

array([1, 2, 3, 4, 5, 6])

- np.delete() --> elimina elementos de un array en posiciones especificas


In [350]:
array = np.array([1, 2, 3, 4, 5])

deleted_array = np.delete(array, 2) #elimino el elemento que esta en la posicion 2

FUNCIONES PARA MANIPULAR ARREGLOS ENTRE SI

- np.vstack() --> apila arrays verticalmente (uno sobre el otro)

In [351]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

vstacked_array = np.vstack((array1, array2))
vstacked_array

array([[1, 2, 3],
       [4, 5, 6]])

- np.hstack() --> apila arrays horizontalmente (uno al lado del otro)


In [352]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

hstacked_array = np.hstack((array1, array2))
hstacked_array

array([1, 2, 3, 4, 5, 6])

- np.concatenate() --> une una secuencia de arrays a lo largo de un eje especifico

In [353]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

concatenated_array = np.concatenate((array1, array2))
concatenated_array

array([1, 2, 3, 4, 5, 6])

### EJERCICIO 5

Los arrays de numpy (así como las listas) proveen de un mecanismo versátil para hacer o referenciar una sección
de los mismos. Practique este mecanismo de acceso con vectores, matrices y tensores imprimiendo y
modificando distintas regiones de los mismos. 

In [354]:
vector = np.array([10,20,30,40,50])


In [355]:
vector[2] #accedo al vector en la pos 2

30

In [356]:
vector[::2] #accedo al vector con paso de 2

array([10, 30, 50])

- Modificacion de secciones

In [357]:
vector[1:4] = [100,200,300] #modifico de la pos 1 a la 3
vector

array([ 10, 100, 200, 300,  50])

MATRICES

In [358]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [359]:
matriz[1,2]

6

In [360]:
matriz[2] #fila en pos 2 de la matriz

array([7, 8, 9])

In [361]:
matriz[:,2] #columna en pos 2 de la matriz

array([3, 6, 9])

In [362]:
matriz[1:3, 1:3] = [[50, 60], [70, 80]] #fila 1,2 columna 1,2
matriz

array([[ 1,  2,  3],
       [ 4, 50, 60],
       [ 7, 70, 80]])

TENSORES

In [363]:
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

In [364]:
tensor[1,0,1]

6

In [365]:
tensor[:2, 1, :] = [[100, 101], [200, 201]]
tensor

array([[[  1,   2],
        [100, 101]],

       [[  5,   6],
        [200, 201]],

       [[  9,  10],
        [ 11,  12]]])

# Pandas

In [366]:
import pandas as pd

Pandas es un paquete de Python que proporciona estructuras de datos rápidas, flexibles y expresivas, diseñadas
para trabajar con datos relacionales o etiquetados. Para comprender el objetivo de Pandas puede revisar el video
https://www.youtube.com/watch?v=gimfTyCNfGw a manera de introducción. Para realizar los ejercicios prácticos
puede consultar el video https://www.youtube.com/watch?v=5S01zSgE9GA. 

### EJERCICIO 1

- Investigue el funcionamiento del Dataframe de Pandas y cree uno con la información de la siguiente tabla:

- Nombre Edad Pais
- Juan 20 Argentina
- María 26 Peru
- Pedro 18 Brasil
- José 22 Chile

Realice las siguientes operaciones:
1. Imprimir los nombres de las columnas.
2. Agregar a la tabla a Pablo que tiene 30 años y es originario de Colombia. Agregarlo de 2 formas diferentes.
3. Eliminar de la tabla al Pedro repetido.
4. Modificar los atributos de países que dicen “Peru” (sin acento) y reemplazarlos por “Perú” (con acento).

In [367]:
data = {
    'Nombre' : ['Juan', 'Maria', 'Pedro', 'Jose'],
    'Edad' : [20,16,18,22],
    'Pais' : ['Argentina', 'Peru', 'Brasil', 'Chile']
}

df = pd.DataFrame(data)
df

Nombre  Edad       Pais
0   Juan    20  Argentina
1  Maria    16       Peru
2  Pedro    18     Brasil
3   Jose    22      Chile

1. Imprimo el nombre de las columnas

In [368]:
df.columns

Index(['Nombre', 'Edad', 'Pais'], dtype='object')

2. Agrego a la tabla a Pablo que tiene 30 anios y es originario de colombia (de dos formas diferentes)

FORMA 1

In [369]:
df.loc[3] = ['Pablo', 30, 'Colombia']
df

Nombre  Edad       Pais
0   Juan    20  Argentina
1  Maria    16       Peru
2  Pedro    18     Brasil
3  Pablo    30   Colombia

FORMA 2

In [370]:
filanueva = pd.DataFrame({'Nombre':['Valeria'], 'Edad': [20], 'Pais':['Argentina']})
df = df.append(filanueva, ignore_index=True)
df

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_5568\390049344.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(filanueva, ignore_index=True)


Nombre  Edad       Pais
0     Juan    20  Argentina
1    Maria    16       Peru
2    Pedro    18     Brasil
3    Pablo    30   Colombia
4  Valeria    20  Argentina

3. Elimino al pablo repetido

In [371]:
df = df.drop(4)
df

Nombre  Edad       Pais
0   Juan    20  Argentina
1  Maria    16       Peru
2  Pedro    18     Brasil
3  Pablo    30   Colombia

4. Modifico Peru sin acento y le agrego la tilde

In [372]:
df.loc[1,'Pais'] = 'Perú'
df

Nombre  Edad       Pais
0   Juan    20  Argentina
1  Maria    16       Perú
2  Pedro    18     Brasil
3  Pablo    30   Colombia

### EJERCICIO 2

Guarde en disco el dataframe del ejercicio anterior en los siguientes formatos:
1. archivo con separación por delimitadores (tabulador como separador).
2. archivo con separación por delimitadores (punto y coma como separador).
3. archivo excel.
4. archivo json.

1. archivo con separacion por delimitadores (tabulador como separador)

In [373]:
df.to_csv('dataframe_tab.csv', sep='\t', index=False)

2. archivo con separación por delimitadores (punto y coma como separador).

In [374]:
df.to_csv('dataframe_punto_coma.csv', sep=';', index=False)

3. excel

In [375]:
df.to_excel('dataframe.xlsx', index=False, engine='openpyxl')

4. json

In [376]:
df.to_json('dataframe.json', orient='records', lines=True)