In [1]:
ColabNotebook = 'google.colab' in str(get_ipython())

if ColabNotebook:
    # monta G-drive en entorno COLAB
    from google.colab import drive
    drive.mount('/content/drive/')

    # carpeta donde se encuentran archivos .py auxiliares
    FUENTES_DIR = '/content/drive/MyDrive/Colab Notebooks/FUENTES/'
    DATOS_DIR = '/content/drive/MyDrive/Colab Notebooks/DATOS/'      # carpeta donde se encuentran los datasets
else:
    # configuración para notebook con instalación LOCAL
    FUENTES_DIR = '../Fuentes'         # carpeta donde se encuentran archivos .py auxiliares
    DATOS_DIR   = '../Datos/' # carpeta donde se encuentran los datasets

# agrega ruta de busqueda donde tenemos archivos .py
import sys
sys.path.append(FUENTES_DIR)

In [2]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 
from tensorflow.keras.utils import to_categorical

import numpy as np
from sklearn import preprocessing, metrics, model_selection 
import pandas as pd

In [3]:
df = pd.read_csv(DATOS_DIR + 'Iris.csv')

# Tomamos todas las columnas menos la última
X = np.array(df.iloc[:, 0:-1])
Y = np.array(df.iloc[:,-1])
encoder = preprocessing.LabelEncoder()
Y = encoder.fit_transform(Y)
print(Y)

etiquetas = encoder.inverse_transform([0,1,2])
print("\n\n Etiquetas = ",etiquetas)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


 Etiquetas =  ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [4]:
#--- CONJUNTOS DE ENTRENAMIENTO Y TESTEO ---
X_train, X_test, Y_train, Y_test = model_selection.train_test_split( \
        X, Y, test_size=0.30) #, random_state=42)

Y_trainB = to_categorical(Y_train)

In [5]:
normalizarEntrada = 1  # 1 si normaliza; 0 si no

if normalizarEntrada:
    # Escala los valores entre 0 y 1
    min_max_scaler = preprocessing.MinMaxScaler()
    X_train = min_max_scaler.fit_transform(X_train)
    X_test = min_max_scaler.transform(X_test)

### Definición del modelo

In [6]:

# Crear un modelo de capas secuenciales
model=Sequential()

# Agregar las capas al modelo
model.add(Dense(2, input_shape=[4], activation='tanh'))
model.add(Dense(3, activation='sigmoid'))

# Imprimir un resumen del modelo
model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 10        
                                                                 
 dense_1 (Dense)             (None, 3)                 9         
                                                                 
Total params: 19
Trainable params: 19
Non-trainable params: 0
_________________________________________________________________


In [7]:
# Configuración para entrenamiento
#model.compile(optimizer='sgd', loss='mse', metrics='accuracy')

model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics='accuracy')


In [8]:
model.fit(X_train,Y_trainB, epochs=500)

Epoch 1/500
4/4 [==============================] - 1s 1ms/step - loss: 1.1388 - accuracy: 0.2476
Epoch 2/500
4/4 [==============================] - 0s 0s/step - loss: 1.1338 - accuracy: 0.2571
Epoch 3/500
4/4 [==============================] - 0s 5ms/step - loss: 1.1284 - accuracy: 0.2571
Epoch 4/500
4/4 [==============================] - 0s 1ms/step - loss: 1.1238 - accuracy: 0.2571
Epoch 5/500
4/4 [==============================] - 0s 2ms/step - loss: 1.1188 - accuracy: 0.2571
Epoch 6/500
4/4 [==============================] - 0s 2ms/step - loss: 1.1148 - accuracy: 0.2667
Epoch 7/500
4/4 [==============================] - 0s 2ms/step - loss: 1.1108 - accuracy: 0.2667
Epoch 8/500
4/4 [==============================] - 0s 0s/step - loss: 1.1078 - accuracy: 0.2667
Epoch 9/500
4/4 [==============================] - 0s 4ms/step - loss: 1.1044 - accuracy: 0.2762
Epoch 10/500
4/4 [==============================] - 0s 2ms/step - loss: 1.1013 - accuracy: 0.2667
Epoch 11/500
4/4 [=============

4/4 [==============================] - 0s 2ms/step - loss: 0.9946 - accuracy: 0.6571
Epoch 85/500
4/4 [==============================] - 0s 2ms/step - loss: 0.9938 - accuracy: 0.6571
Epoch 86/500
4/4 [==============================] - 0s 2ms/step - loss: 0.9920 - accuracy: 0.6667
Epoch 87/500
4/4 [==============================] - 0s 3ms/step - loss: 0.9906 - accuracy: 0.6667
Epoch 88/500
4/4 [==============================] - 0s 2ms/step - loss: 0.9893 - accuracy: 0.6667
Epoch 89/500
4/4 [==============================] - 0s 2ms/step - loss: 0.9884 - accuracy: 0.6857
Epoch 90/500
4/4 [==============================] - 0s 2ms/step - loss: 0.9863 - accuracy: 0.6762
Epoch 91/500
4/4 [==============================] - 0s 2ms/step - loss: 0.9850 - accuracy: 0.6762
Epoch 92/500
4/4 [==============================] - 0s 2ms/step - loss: 0.9838 - accuracy: 0.6762
Epoch 93/500
4/4 [==============================] - 0s 3ms/step - loss: 0.9822 - accuracy: 0.6762
Epoch 94/500
4/4 [===============

4/4 [==============================] - 0s 1ms/step - loss: 0.8524 - accuracy: 0.6952
Epoch 168/500
4/4 [==============================] - 0s 2ms/step - loss: 0.8504 - accuracy: 0.6857
Epoch 169/500
4/4 [==============================] - 0s 2ms/step - loss: 0.8484 - accuracy: 0.6952
Epoch 170/500
4/4 [==============================] - 0s 1ms/step - loss: 0.8464 - accuracy: 0.6857
Epoch 171/500
4/4 [==============================] - 0s 4ms/step - loss: 0.8448 - accuracy: 0.6857
Epoch 172/500
4/4 [==============================] - 0s 1ms/step - loss: 0.8422 - accuracy: 0.6857
Epoch 173/500
4/4 [==============================] - 0s 1ms/step - loss: 0.8403 - accuracy: 0.6857
Epoch 174/500
4/4 [==============================] - 0s 4ms/step - loss: 0.8383 - accuracy: 0.6857
Epoch 175/500
4/4 [==============================] - 0s 2ms/step - loss: 0.8361 - accuracy: 0.6857
Epoch 176/500
4/4 [==============================] - 0s 2ms/step - loss: 0.8340 - accuracy: 0.6952
Epoch 177/500
4/4 [=====

4/4 [==============================] - 0s 2ms/step - loss: 0.6868 - accuracy: 0.6952
Epoch 250/500
4/4 [==============================] - 0s 2ms/step - loss: 0.6849 - accuracy: 0.6952
Epoch 251/500
4/4 [==============================] - 0s 2ms/step - loss: 0.6831 - accuracy: 0.6952
Epoch 252/500
4/4 [==============================] - 0s 2ms/step - loss: 0.6813 - accuracy: 0.6952
Epoch 253/500
4/4 [==============================] - 0s 2ms/step - loss: 0.6795 - accuracy: 0.6952
Epoch 254/500
4/4 [==============================] - 0s 2ms/step - loss: 0.6778 - accuracy: 0.6952
Epoch 255/500
4/4 [==============================] - 0s 2ms/step - loss: 0.6759 - accuracy: 0.6952
Epoch 256/500
4/4 [==============================] - 0s 2ms/step - loss: 0.6742 - accuracy: 0.6952
Epoch 257/500
4/4 [==============================] - 0s 2ms/step - loss: 0.6726 - accuracy: 0.6952
Epoch 258/500
4/4 [==============================] - 0s 3ms/step - loss: 0.6708 - accuracy: 0.6952
Epoch 259/500
4/4 [=====

4/4 [==============================] - 0s 2ms/step - loss: 0.5661 - accuracy: 0.7810
Epoch 332/500
4/4 [==============================] - 0s 3ms/step - loss: 0.5648 - accuracy: 0.7905
Epoch 333/500
4/4 [==============================] - 0s 0s/step - loss: 0.5635 - accuracy: 0.8000
Epoch 334/500
4/4 [==============================] - 0s 4ms/step - loss: 0.5624 - accuracy: 0.8190
Epoch 335/500
4/4 [==============================] - 0s 1ms/step - loss: 0.5612 - accuracy: 0.8095
Epoch 336/500
4/4 [==============================] - 0s 1ms/step - loss: 0.5601 - accuracy: 0.8095
Epoch 337/500
4/4 [==============================] - 0s 682us/step - loss: 0.5590 - accuracy: 0.8190
Epoch 338/500
4/4 [==============================] - 0s 1ms/step - loss: 0.5581 - accuracy: 0.8190
Epoch 339/500
4/4 [==============================] - 0s 728us/step - loss: 0.5569 - accuracy: 0.8286
Epoch 340/500
4/4 [==============================] - 0s 2ms/step - loss: 0.5557 - accuracy: 0.8286
Epoch 341/500
4/4 [==

4/4 [==============================] - 0s 0s/step - loss: 0.4904 - accuracy: 0.8952
Epoch 414/500
4/4 [==============================] - 0s 3ms/step - loss: 0.4895 - accuracy: 0.8857
Epoch 415/500
4/4 [==============================] - 0s 0s/step - loss: 0.4889 - accuracy: 0.8857
Epoch 416/500
4/4 [==============================] - 0s 4ms/step - loss: 0.4881 - accuracy: 0.8952
Epoch 417/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4878 - accuracy: 0.8857
Epoch 418/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4867 - accuracy: 0.8857
Epoch 419/500
4/4 [==============================] - 0s 784us/step - loss: 0.4859 - accuracy: 0.8857
Epoch 420/500
4/4 [==============================] - 0s 875us/step - loss: 0.4852 - accuracy: 0.8857
Epoch 421/500
4/4 [==============================] - 0s 354us/step - loss: 0.4844 - accuracy: 0.8857
Epoch 422/500
4/4 [==============================] - 0s 0s/step - loss: 0.4836 - accuracy: 0.8857
Epoch 423/500
4/4 [==

4/4 [==============================] - 0s 4ms/step - loss: 0.4367 - accuracy: 0.8857
Epoch 497/500
4/4 [==============================] - 0s 815us/step - loss: 0.4361 - accuracy: 0.8857
Epoch 498/500
4/4 [==============================] - 0s 0s/step - loss: 0.4356 - accuracy: 0.8857
Epoch 499/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4351 - accuracy: 0.8857
Epoch 500/500
4/4 [==============================] - 0s 702us/step - loss: 0.4346 - accuracy: 0.8857


In [9]:
# Evaluación del modelo
score = model.evaluate(X_train, Y_trainB) 

print('Error :', score[0]) 
print('Accuracy:', score[1])


4/4 [==============================] - 0s 6ms/step - loss: 0.4339 - accuracy: 0.8857
Error : 0.4339439272880554
Accuracy: 0.8857142925262451


In [10]:
# predecir la salida del modelo
Y_pred = model.predict(X_train)

# Convertir la salida del modelo en un número entero
Y_pred2 = np.argmax(Y_pred,axis=1)

print("%% aciertos : %.3f" % metrics.accuracy_score(Y_train, Y_pred2))
print(Y_pred[:5,:])
print(Y_pred2[:5])

4/4 [==============================] - 0s 3ms/step
% aciertos : 0.886
[[0.2345884  0.64300555 0.52718264]
 [0.89703166 0.4765947  0.22521856]
 [0.9261241  0.43125385 0.21558857]
 [0.05265177 0.6232599  0.7600478 ]
 [0.07285985 0.6559295  0.69804806]]
[1 0 0 2 2]


In [11]:
report = metrics.classification_report(Y_train, Y_pred2, target_names=etiquetas)
print("Training metrics:\n%s" % report) 

MM = metrics.confusion_matrix(Y_train, Y_pred2)
print("Confusion matrix:\n%s" % MM)

Training metrics:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        36
Iris-versicolor       0.83      0.83      0.83        36
 Iris-virginica       0.82      0.82      0.82        33

       accuracy                           0.89       105
      macro avg       0.88      0.88      0.88       105
   weighted avg       0.89      0.89      0.89       105

Confusion matrix:
[[36  0  0]
 [ 0 30  6]
 [ 0  6 27]]


In [12]:
# predecir la salida del modelo
Y_pred = model.predict(X_test)
Y_pred2 = np.argmax(Y_pred,axis=1)

print("%% aciertos X_train : %.3f" % metrics.accuracy_score(Y_test, Y_pred2))

2/2 [==============================] - 0s 0s/step
% aciertos X_train : 0.800


In [13]:
report = metrics.classification_report(Y_test, Y_pred2, target_names=etiquetas)

print("Métricas de la clasificación:\n%s" % report) 

Métricas de la clasificación:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       0.73      0.57      0.64        14
 Iris-virginica       0.70      0.82      0.76        17

       accuracy                           0.80        45
      macro avg       0.81      0.80      0.80        45
   weighted avg       0.80      0.80      0.80        45



In [14]:
MM = metrics.confusion_matrix(Y_test, Y_pred2)

print("Confusion matrix:\n%s" % MM)
# Convertimos la matriz de confusión en un DataFrame con etiquetas
df_cm = pd.DataFrame(MM, index=etiquetas, columns=etiquetas)

# Mostramos el DataFrame resultante
print("\n\n",df_cm)

Confusion matrix:
[[14  0  0]
 [ 0  8  6]
 [ 0  3 14]]


                  Iris-setosa  Iris-versicolor  Iris-virginica
Iris-setosa               14                0               0
Iris-versicolor            0                8               6
Iris-virginica             0                3              14


In [15]:
capaOculta = model.layers[0]
W1, b1 = capaOculta.get_weights()

capaSalida = model.layers[1]
W2,b2 = capaSalida.get_weights()

print("W1")
print(W1)

print("b1")
print(b1)

print("W2")
print(W2)

print("b2")
print(b2)

W1
[[ 0.58010274  1.3853815 ]
 [-1.4737184  -0.57723176]
 [ 0.30808493  0.83718336]
 [ 1.2900784   0.49798584]]
b1
[ 0.2513385  -0.95819956]
W2
[[-2.0893924   1.114096    0.26943678]
 [-1.6383313  -0.49732807  1.3459902 ]]
b2
[ 0.21140951 -0.07140561 -0.14000352]


In [16]:
#model.save("IRIS_Sigmoid.h5")